server:
  port: 8080
  servlet:
    context-path: /api

app:
  services:
    model: "https://unilabpass.hpcc.vn/model"
  Global:
    VNHour: 7
    RemainVerify: 3

spring:
  datasource:
    url: "jdbc:postgresql://dpg-cvdho32n91rc739kj7p0-a.oregon-postgres.render.com:5432/unilab_pass_ltu2"

    username: unilab_pass_ltu2_user
    password: ${DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "nguyenducanhtuan0602@gmail.com"
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 50MB
verification-code:
  email:
    character: "123456789"
    code-length: 6
jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: 1800 # in seconds
  refreshable-duration: 3600 # in seconds
cloudinary:
  url: ${CLOUDINARY_URL}