server:
  port: 8080
  servlet:
    context-path: /identity

app:
  Global:
    VNHour: 7

spring:
  datasource:
    url: "jdbc:postgresql://dpg-cvdho32n91rc739kj7p0-a.oregon-postgres.render.com:5432/unilab_pass_ltu2"

    username: unilab_pass_ltu2_user
    password: bajQQw1pkOEo4YiQqi9oPS6DvFZGY6y2
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "nguyenducanhtuan0602@gmail.com"
    password: "vceoxockfgoxtngg"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
verification-code:
  email:
    character: "123456789"
    code-length: 6
jwt:
  signerKey: "FZ53SRj+TB9MIVipkwxSeNxG4SIE7JQU/LPjLxuWrwoUfn7WQRBahoVphiyS30pa"
  valid-duration: 1800 # in seconds
  refreshable-duration: 3600 # in seconds

cloudinary:
  cloud-name: 'dpm9uyvug'
  api-key: '172917998967798'
  api-secret: '1ZZduwXvtr_lIhpq2ckpXsfyaRM'