server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "nguyenducanhtuan0602@gmail.com"
    password: "vceoxockfgoxtngg"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
verification-code:
  email:
    character: "123456789"
    code-length: 6
jwt:
  signerKey: "FZ53SRj+TB9MIVipkwxSeNxG4SIE7JQU/LPjLxuWrwoUfn7WQRBahoVphiyS30pa"
  valid-duration: 20 # in seconds
  refreshable-duration: 120 # in seconds