server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:postgresql://dpg-cup38r56l47c73cii7s0-a.oregon-postgres.render.com:5432/unilab_pass"
    username: unilab_pass_user
    password: YbfqbZYVRcCDJx6g8XMpSwfCOAigeE86
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "nguyenducanhtuan0602@gmail.com"
    password: "vceoxockfgoxtngg"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
verification-code:
  email:
    character: "123456789"
    code-length: 6
jwt:
  signerKey: "FZ53SRj+TB9MIVipkwxSeNxG4SIE7JQU/LPjLxuWrwoUfn7WQRBahoVphiyS30pa"
  valid-duration: 20 # in seconds
  refreshable-duration: 360 # in seconds
